### ISSUE TITLE
Example does not work if workspace is not in eastus

### ISSUE THREAD

**Issue by dkmiller** [Azure/aml-object-recognition-pipeline#1]
I tried a basic walkthrough of this example, with workspace in the region northcentralus. Since the file `data_ingestion.py` hard-codes the cognitive services endpoint, the "Data Ingestion" step fails with error:

> User program failed with HTTPError: 401 Client Error: Access Denied for url: https://eastus.api.cognitive.microsoft.com/bing/v7.0/images/search?q=airplane&imageType=photo&count=150&offset=0

**Comment by dkmiller** [comment]
@sanpil

**Comment by sanpil** [comment]
This is a known issue. Please send a PR if you have spare time to fix.

**Comment by dkmiller** [comment]
Opening #3 .
